# Generated by Django 3.2.7 on 2021-09-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('age', models.CharField(max_length=20)),
                ('place', models.TextField()),
                ('description', models.TextField()),
                ('found', models.BooleanField(default=False)),
            ],
        ),
    ]
